-- Dholera Smart City Projects Table Migration Script
-- Developed by Expert Database Architect

-- 1. Create Projects Table Schema
CREATE TABLE IF NOT EXISTS `projects` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `category` VARCHAR(150) NOT NULL,
  `rating` DECIMAL(2,1) DEFAULT 4.5,
  `reviews` VARCHAR(50) DEFAULT '0',
  `location` VARCHAR(255) NOT NULL,
  `main_image` VARCHAR(255) NOT NULL,
  `thumbs` TEXT, -- JSON array of extra thumbnail image paths
  `price` VARCHAR(100) NOT NULL,
  `price_sub` VARCHAR(255) NOT NULL,
  `rera` VARCHAR(150) NOT NULL,
  `size` VARCHAR(100) NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  `road` VARCHAR(150) NOT NULL,
  `power` VARCHAR(150) NOT NULL,
  `water` VARCHAR(150) NOT NULL,
  `description` TEXT NOT NULL,
  `amenities` TEXT, -- JSON array of amenities checklist
  `seo_title` VARCHAR(255) DEFAULT NULL,
  `seo_description` TEXT DEFAULT NULL,
  `seo_keywords` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Seed Default Projects Data
INSERT INTO `projects` (
  `id`, `title`, `category`, `rating`, `reviews`, `location`, `main_image`, `thumbs`, 
  `price`, `price_sub`, `rera`, `size`, `status`, `road`, `power`, `water`, `description`, `amenities`,
  `seo_title`, `seo_description`, `seo_keywords`
) VALUES 
(
  1,
  'Mastering Dholera Ring Road Residential Villas [Phase 1]',
  'Residential Villa Plots',
  4.5,
  '565',
  'Smart City Ring Road, Dholera SIR',
  'assets/images/hero-bg.png',
  '["assets/images/hero-bg.png","assets/images/banner2.png","assets/images/banner3.png"]',
  '₹1,499 / Sq.Yd',
  'Plot sizes starting at 120 Sq.Yd',
  'PR/GJ/AHMEDABAD/DSIR/00123/2026',
  '120 - 500 Sq.Yd',
  'Immediate Possession',
  '12 Meter Wide Paved Roads',
  'Smart Solar Grid Net-Metering',
  'Recycled Utility Grid Supply',
  'Dholera Smart City Ring Road Residential Villas (Phase 1) represents a premier residential landmark inside the activation zone. Positioned strategically adjacent to the main express ring road, this registry-ready development provides a unique baseline of high-end living parameters and smart urban infrastructure.<br><br>Every single plot inside the phase 1 block is fully mapped under the central ICT utility layout, meaning water lines, electricity terminals, solar net-metering grids, and high-speed gigabit fiber pathways are pre-installed directly to your boundary line prior to purchase. This plug-and-play capability ensures a seamless residential villa build with zero administrative hassle.',
  '["Smart Utility Grids","24\\/7 CCTV & Boundary Walls","Landscaped Parks","Solar Street Lighting","Rainwater Harvesting","Clubhouse Arena","Paved Jogging Tracks","Underground Cabling Grid"]',
  'Dholera Ring Road Residential Villas [Phase 1] - Smart Plots',
  'Explore Dholera Smart City Ring Road Residential Villas Phase 1. Registry-ready residential plots equipped with plug-and-play solar and fiber grids.',
  'dholera plots, dholera residential, dholera smart city, dholera ring road plots'
),
(
  2,
  'GenAI & AI Industrial Plots for QA Automation | Copilot & Claude...',
  'Industrial Economic Land',
  4.5,
  '17984',
  'Industrial Zone Block A, Dholera SIR',
  'assets/images/banner2.png',
  '["assets/images/banner2.png","assets/images/hero-bg.png","assets/images/banner3.png"]',
  '₹3,999 / Sq.Yd',
  'Industrial sectors starting at 1,000 Sq.Yd',
  'PR/GJ/AHMEDABAD/DSIR/00889/2026',
  '1,000 - 10,000 Sq.Yd',
  'Ready for Construction',
  '30 Meter Wide Cargo Highways',
  'Dedicated High-Voltage Substation',
  'Industrial Recycled Water Line',
  'The GenAI & AI Industrial Park in Block A is the crown jewel of manufacturing and corporate infrastructure inside Dholera SIR. Specifically engineered to host smart production assemblies, clean data centers, warehousing complexes, and logistics hubs, this premium sector delivers plug-and-play capabilities with immediate custom approvals.<br><br>Boasting ultra-high weight tolerances for road corridors and dual-line dedicated power grids directly supported by national solar grid substations, this zone represents India\'s forward-thinking approach to next-generation clean industrialization along the Delhi-Mumbai Economic Corridor.',
  '["Dual-Line High Voltage","30M Cargo Pathways","Single-Window Licensing","Industrial Waste Lines","ICT Telecom Fiber Grid","Fire Fighting Substation","Helipad Access","Logistics Cargo Hub"]',
  'GenAI & AI Industrial Plots for QA Automation - Dholera SIR',
  'Premium manufacturing and clean data center industrial plots in Block A, Dholera SIR. Single-window approvals and adjacent international airport links.',
  'dholera industrial plots, industrial land dholera, dholera sir block a'
),
(
  3,
  'Coding With Infra - Planning To Sustainable Industrial Production',
  'Commercial Infrastructure Space',
  4.8,
  '513',
  'Central Business District, Dholera SIR',
  'assets/images/banner3.png',
  '["assets/images/banner3.png","assets/images/thumb4.png","assets/images/thumb5.png"]',
  '₹4,499 / Sq.Yd',
  'Commercial plots starting at 300 Sq.Yd',
  'PR/GJ/AHMEDABAD/DSIR/00342/2026',
  '300 - 1,200 Sq.Yd',
  'Immediate Registration',
  '18 Meter Wide Double Pathways',
  '24/7 Uninterrupted Backed Grid',
  'Central Drinking Water Connection',
  'Positioned right inside the Central Business District (CBD) of Dholera Special Investment Region, this commercial infrastructure layout zone is built to scale high-tech offices, business hotels, retail complexes, and administrative towers.<br><br>As part of Dholera\'s primary commercial corridor, this development stands out with optimized floor-space indices (FSI), centralized climate cooling grids, and direct walkable links to the primary city high-speed metro terminal, representing a prestigious address for any modern enterprise.',
  '["Walkable Metro Proximity","Central Climate Cooling","Optimized Higher FSI","Underground Utility Shafts","High-Speed Fiber Network","Valet Parking Arena","Conference Clubhouse","Multi-Tier Cyber Security"]',
  'CBD Commercial Infrastructure Plots & Corporate Spaces - Dholera',
  'Central Business District commercial plots inside Dholera SIR. High FSI limits, centralized cooling, and direct walkability to high-speed metro lines.',
  'dholera commercial plots, cbd dholera sir, dholera offices land'
),
(
  4,
  'Make from beginner to pro - Residential Plots & Smart Townships',
  'Premium Residential Land',
  4.5,
  '461',
  'Premium Township Zone C, Dholera SIR',
  'assets/images/thumb4.png',
  '["assets/images/thumb4.png","assets/images/banner2.png","assets/images/hero-bg.png"]',
  '₹1,299 / Sq.Yd',
  'Premium plots starting at 150 Sq.Yd',
  'PR/GJ/AHMEDABAD/DSIR/00744/2026',
  '150 - 600 Sq.Yd',
  'Possession in 3 Months',
  '15 Meter Wide Landscaped Roads',
  'Hybrid Solar-Wind Micro Grid',
  'Central Softened Water Connection',
  'Dholera Smart Greens Residency represents a tranquil, modern eco-township concept. Positioned inside the eco-friendly residential zone C, it features vast botanical landscapes, automated garbage disposal structures, smart security sensors, and premium recreational amenities.<br><br>Built for young families and investors seeking sustainable property yields, Dholera Greens sets a benchmark with high-class construction standardizations, underground utility routing, and immediate registries backed fully by government land bank clearances.',
  '["Botanical Gardens","Automated Garbage Shafts","Smart Clubhouse & Gym","Swimming Pool Arena","Basketball & Tennis Courts","Central Softened Water","24\\/7 Security Patrol","Jogging & Cycling Paths"]',
  'Smart Greens Residency & Premium Residential Plots - Dholera',
  'Eco-friendly residential land and smart townships in Zone C, Dholera. Botanical parks, organic green security, and hybrid micro solar grids.',
  'dholera residential plots, smart greens township dholera, zone c plots'
),
(
  5,
  'Advanced Greenfield Logistics - Warehousing & Commercial Zones [2026]',
  'Logistics & Warehousing Land',
  4.7,
  '382',
  'Logistics Park Phase 2, Dholera SIR',
  'assets/images/thumb5.png',
  '["assets/images/thumb5.png","assets/images/banner3.png","assets/images/hero-bg.png"]',
  '₹2,999 / Sq.Yd',
  'Logistics sectors starting at 2,000 Sq.Yd',
  'PR/GJ/AHMEDABAD/DSIR/00912/2026',
  '2,000 - 25,000 Sq.Yd',
  'Immediate Registration',
  '45 Meter Wide Multi-Lane Highway',
  'Substation Connected Dedicated Grid',
  'High Volume Industrial Connection',
  'Engineered to act as a major supply chain valve inside DSIR, this Logistics and Warehousing Zone in Phase 2 offers massive industrial plots optimized for bulk cargo handling, distribution networks, automated cold-storage facilities, and cargo rail connectivity.<br><br>Located directly adjacent to the dedicated freight corridor and the upcoming Dholera International Airport expressway, it provides unmatched logistical efficiencies for export-oriented manufacturing firms and retail e-commerce giants.',
  '["Dedicated Freight Link","Multi-Lane Expressways","Cold-Storage Utilities","High-Load Floor Strength","Border Security Customs","ICT Cargo Control Desk","Heavy Vehicle Parking","24\\/7 Emergency Services"]',
  'Logistics & Bulk Warehousing Plots - Dholera SIR [2026]',
  'Massive industrial logistics and warehousing land inside Dholera SIR. Direct rail connections, dedicated freight highway access, and customs clearing portals.',
  'dholera logistics plots, warehousing land dholera, dholera freight corridor'
)
ON DUPLICATE KEY UPDATE `title` = `title`;
